### ISSUE TITLE
It show's me error

### ISSUE THREAD

**Issue by ghost** [laidig/nyct-gtfs-rt-example#1]
com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:78)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:498)
	at com.google.protobuf.GeneratedMessage$Builder.parseUnknownField(GeneratedMessage.java:438)
	at com.google.transit.realtime.GtfsRealtime$FeedMessage$Builder.mergeFrom(GtfsRealtime.java:449)
	at com.google.transit.realtime.GtfsRealtime$FeedMessage$Builder.mergeFrom(GtfsRealtime.java:266)
	at com.google.protobuf.AbstractMessageLite$Builder.mergeFrom(AbstractMessageLite.java:212)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:746)
	at com.google.transit.realtime.GtfsRealtime$FeedMessage.parseFrom(GtfsRealtime.java:217)
	at net.transitdata.gtfsRTNYCT.Main.main(Main.java:23)

**Comment by laidig** [comment]
Did you put in the environment variable?

How you set that depends on your execution environment or IDE (IntelliJ, Eclipse, etc). It should be searchable.
